### ISSUE TITLE
Ethernet address anonymization

### ISSUE THREAD

**Issue by Pesa** [usnistgov/ndntdump#2]
When capturing intranet traffic, it is important to anonymize source/destination addresses in the Ethernet header. We could either scramble the whole address or just the lower 3 bytes. In the latter case, we would keep the vendor ID in the trace, although I don't see a use case for this at the moment.

I think this anonymization should be enabled by default with an opt-out flag for specific scenarios or testing purposes.

**Comment by Pesa** [comment]
See also https://www.icir.org/enterprise-tracing/devil-ccr-jan06.pdf

**Comment by yoursunny** [comment]
This program was initially designed for ndn6 network, where NFD runs in containers that have random MAC addresses.
Given it's now being used on physical machines, I have added this feature.
